# Set update schedule for GitHub Actions
version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions
      interval: "weekly"
      day: "tuesday"
    ignore:
      # Ignore patch updates for actions/cache
      - dependency-name: "actions/cache"
        update-types: ["version-update:semver-patch"]
