blank_issues_enabled: false
contact_links:
  - name: Sandboxie documentation (sandboxie-plus/sandboxie-docs)
    url: https://github.com/sandboxie-plus/sandboxie-docs
    about: GitHub documentation for people interested in Sandboxie.
  - name: LogApiDll (sandboxie-plus/LogApiDll)
    url: https://github.com/sandboxie-plus/LogApiDll
    about: API logging library that adds a verbose output to Sandboxie's trace log.
  - name: Sbiextra (sandboxie-plus/sbiextra)
    url: https://github.com/sandboxie-plus/sbiextra
    about: A DLL that adds additional user mode restrictions to sandboxed processes.
